Shopping/Controllers/TbBillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shopping.Models.db;

namespace Shopping.Controllers
{
    public class TbBillsController : Controller
    {
        private readonly ShoppingContext _context;

        public TbBillsController(ShoppingContext context)
        {
            _context = context;
        }

        // GET: TbBills
        public async Task<IActionResult> Index()
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;
            if (TempData["UserName"] != null)
            {
                var shoppingContext = _context.TbBill.Include(t => t.Cus).Include(t => t.Pd);
                TempData.Keep();
                return View(await shoppingContext.ToListAsync());
            }
            else
            {
                TempData.Keep();
                return RedirectToAction("Index", "Admin");
            }

        }

        public ActionResult Logout()
        {
            TempData.Clear();
            return RedirectToAction("Index", "Admin");
        }

        // GET: TbBills/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;
            if (TempData["UserName"] != null)
            {
                if (id == null)
                {
                    TempData.Keep();
                    return NotFound();
                }

                var tbBill = await _context.TbBill
                    .Include(t => t.Cus)
                    .Include(t => t.Pd)
                    .FirstOrDefaultAsync(m => m.BillId == id);
                if (tbBill == null)
                {
                    TempData.Keep();
                    return NotFound();
                }
                TempData.Keep();
                return View(tbBill);
            }
            else
            {
                TempData.Keep();
                return RedirectToAction("Index", "Admin");
            }

        }

        // POST: TbBills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;

            var tbBill = await _context.TbBill.FindAsync(id);
            _context.TbBill.Remove(tbBill);
            await _context.SaveChangesAsync();
            TempData.Keep();
            return RedirectToAction(nameof(Index));
        }

        private bool TbBillExists(int id)
        {
            return _context.TbBill.Any(e => e.BillId == id);
        }


        public IActionResult Searchbox(string query)
        {
            {
                
                TempData.Keep();
                var nav = 2;
                ViewBag.nav = nav;
                if (string.IsNullOrEmpty(query))
                {
                    TempData.Keep();
                    return View("Index", _context.TbBill.ToList());

                }
                else
                {
                    TempData.Keep();
                    return View("Index", _context.TbBill.Where(p => p.Cus.CusName.Contains(query)).ToList());
                }
            }
        }
    }
}

Shopping/Controllers/TbCustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shopping.Models.db;

namespace Shopping.Controllers
{
    public class TbCustomersController : Controller
    {
        private readonly ShoppingContext _context;

        public TbCustomersController(ShoppingContext context)
        {
            _context = context;
        }

        // GET: TbCustomers
        public async Task<IActionResult> Index()
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;
            if (TempData["UserName"] != null)
            {
                TempData.Keep();
                return View(await _context.TbCustomer.ToListAsync());
            }
            else
            {
                TempData.Keep();
                return RedirectToAction("Index", "Admin");
            }


        }

        public ActionResult Logout()
        {
            TempData.Clear();
            return RedirectToAction("Index", "Admin");
        }

        // GET: TbCustomers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;

            if (id == null)
            {
                TempData.Keep();
                return NotFound();
            }

            var tbCustomer = await _context.TbCustomer
                .FirstOrDefaultAsync(m => m.CusId == id);
            if (tbCustomer == null)
            {
                TempData.Keep();
                return NotFound();
            }
            TempData.Keep();
            return View(tbCustomer);
        }

        // POST: TbCustomers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;


                var tbCustomer = await _context.TbCustomer.FindAsync(id);
                _context.TbCustomer.Remove(tbCustomer);
                await _context.SaveChangesAsync();
                TempData.Keep();
                return RedirectToAction(nameof(Index));



        }

        private bool TbCustomerExists(int id)
        {
            return _context.TbCustomer.Any(e => e.CusId == id);
        }


        public IActionResult Searchbox(string query)
        {
            {
                TempData.Keep();
                var nav = 2;
                ViewBag.nav = nav;
                if (string.IsNullOrEmpty(query))
                {
                    TempData.Keep();
                    return View("Index", _context.TbCustomer.ToList());

                }
                else
                {
                    TempData.Keep();
                    return View("Index", _context.TbCustomer.Where(p => p.CusName.Contains(query)).ToList());
                }
            }
        }
    }
}

Shopping/Controllers/TbProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shopping.Models.db;

namespace Shopping.Controllers
{
    public class TbProductsController : Controller
    {
        private readonly ShoppingContext _context;

        public TbProductsController(ShoppingContext context)
        {
            _context = context;
        }

        // GET: TbProducts
        public async Task<IActionResult> Index()
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;

            if (TempData["UserName"] != null)
            {
                var shoppingContext = _context.TbProduct.Include(t => t.Cate);
                TempData.Keep();
                return View(await shoppingContext.ToListAsync());
            }
            else
            {
                TempData.Keep();
                return RedirectToAction("Index", "Admin");
            }

        }

        public ActionResult Logout()
        {
            TempData.Clear();
            return RedirectToAction("Index", "Admin");
        }

        // GET: TbProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbProduct = await _context.TbProduct
                .Include(t => t.Cate)
                .FirstOrDefaultAsync(m => m.PdId == id);
            if (tbProduct == null)
            {
                return NotFound();
            }

            return View(tbProduct);
        }

        // GET: TbProducts/Create
        public IActionResult Create()
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;

            if (TempData["UserName"] != null)
            {
                ViewData["CateId"] = new SelectList(_context.TbCategory, "CateId", "CateName");
                TempData.Keep();
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }

        }

        // POST: TbProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PdId,PdImg,PdName,PdPrice,PdStock,PdStatus,CateId,PdDetail,PdSubHead,PdDelete")] TbProduct tbProduct, List<IFormFile> PdImg)
        {
            TempData.Keep();

            if (ModelState.IsValid)
            {
                foreach (var item in PdImg)
                {
                    if (item.Length > 0)
                    {
                        using (var stream = new MemoryStream())
                        {
                            await item.CopyToAsync(stream);
                            tbProduct.PdImg = stream.ToArray();
                        }
                    }
                }

                _context.Add(tbProduct);
                await _context.SaveChangesAsync();
                TempData.Keep();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CateId"] = new SelectList(_context.TbCategory, "CateId", "CateName", tbProduct.CateId);
            TempData.Keep();
            return View(tbProduct);
        }

        // GET: TbProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;

            if (TempData["UserName"] != null)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var tbProduct = await _context.TbProduct.FindAsync(id);
                if (tbProduct == null)
                {
                    return NotFound();
                }
                ViewData["CateId"] = new SelectList(_context.TbCategory, "CateId", "CateName", tbProduct.CateId);
                TempData.Keep();
                return View(tbProduct);
            }
            else
            {
                TempData.Keep();
                return RedirectToAction("Index", "Admin");
            }

        }

        // POST: TbProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PdId,PdImg,PdName,PdPrice,PdStock,PdStatus,CateId,PdDetail,PdSubHead,PdDelete")] TbProduct tbProduct, List<IFormFile> PdImg)
        {
            if (id != tbProduct.PdId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    foreach (var item in PdImg)
                    {
                        if (item.Length > 0)
                        {
                            using (var stream = new MemoryStream())
                            {
                                await item.CopyToAsync(stream);
                                tbProduct.PdImg = stream.ToArray();
                            }
                        }
                    }

                    _context.Update(tbProduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbProductExists(tbProduct.PdId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData.Keep();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CateId"] = new SelectList(_context.TbCategory, "CateId", "CateName", tbProduct.CateId);
            TempData.Keep();
            return View(tbProduct);
        }

        // GET: TbProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            TempData.Keep();
            var nav = 2;
            ViewBag.nav = nav;

            if (TempData["UserName"] != null)
            {
                if (id == null)
                {
                    TempData.Keep();
                    return NotFound();
                }

                var tbProduct = await _context.TbProduct
                    .Include(t => t.Cate)
                    .FirstOrDefaultAsync(m => m.PdId == id);
                if (tbProduct == null)
                {
                    TempData.Keep();
                    return NotFound();
                }
                TempData.Keep();
                return View(tbProduct);
            }
            else
            {
                TempData.Keep();
                return RedirectToAction("Index", "Admin");
            }

        }

        // POST: TbProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            TempData.Keep();
            var tbProduct = await _context.TbProduct.FindAsync(id);
            _context.TbProduct.Remove(tbProduct);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbProductExists(int id)
        {
            return _context.TbProduct.Any(e => e.PdId == id);
        }

        public IActionResult Searchbox(string query)
        {
            {
                TempData.Keep();
                var nav = 2;
                ViewBag.nav = nav;
                if (string.IsNullOrEmpty(query))
                {
                    TempData.Keep();
                    return View("Index", _context.TbProduct.ToList());

                }
                else
                {
                    TempData.Keep();
                    return View("Index", _context.TbProduct.Where(p => p.PdName.Contains(query)).ToList());
                }
            }
        }
    }
}

Shopping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/nav-bar.css">
    <link rel="stylesheet" href="~/css/footer2.css">
    <link rel="stylesheet" href="~/js/CheckSearchbox.js" />
    <link rel="stylesheet" href="~/css/ProductAdmin.css">




</head>

<body>
    <!--------------------Navigation bar------------------------->

    <header>
        @if (ViewBag.nav == 1)
        {
            <nav class="navbar navbar-dark container-fluid navbar-expand-sm fixed-top nav-bar">
                <div class="container">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-logo my-2"><img src="~/icon/FilmLab.svg" class="logo-nav-img"></a>
                    @* Searchbox *@
                    <form id="f_search" method="get" asp-controller="Home" asp-action="Searchbox" class="input-group search-box col-lg-8 col-md-6 col-sm-4">
                        <input d="ipt_search" type="text" class="form-control search-field" placeholder="Search" name="querry">
                        <div class="input-group-append">
                            <button type="submit" id="btnsearch" class="btn btn-secondary btn-search-nav">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </form>

                    <div>
                        <ul class="navbar-nav">
                            <li class="nav-item active d-flex align-items-center ml-md-12">
                                <a asp-area="" asp-controller="Home" asp-action="ProductCategory" class="nav-link btn btn-nav my-2 my-sm-0" role="button">Shop</a>
                            </li>
                            <li class="nav-item cart-icon ml-md-4">
                                <a asp-area="" asp-controller="Home" asp-action="Cart" style="text-decoration: none; color: #F2E5D5;">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="2.938rem" viewBox="0 0 24 24" width="2.563rem"><path d="M0 0h24v24H0z" fill="none" /><path d="M7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zM1 2v2h2l3.6 7.59-1.35 2.45c-.16.28-.25.61-.25.96 0 1.1.9 2 2 2h12v-2H7.42c-.14 0-.25-.11-.25-.25l.03-.12.9-1.63h7.45c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.08-.14.12-.31.12-.48 0-.55-.45-1-1-1H5.21l-.94-2H1zm16 16c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z" /></svg>
                                    @if (TempData["item_count"] == null)
                                    {
                                        <p>(0)</p>
                                    }
                                    else
                                    {
                                        <p class="RobotoFont">(@TempData["item_count"])</p>
                                    }

                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
        else
        {
            <nav class="navbar navbar-dark container-fluid navbar-expand-sm fixed-top nav-bar">
                <div class="container">
                    <a asp-area="" asp-controller="TbProducts" asp-action="Index" class="nav-logo my-2"><img src="~/icon/FilmLabAdmin.svg" class="logo-nav-img"></a>

                    <div>
                        <ul class="nav justify-content-center navAdmin ">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="TbProducts" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="TbCustomers" asp-action="Index" class="nav-link">Customers</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="TbBills" asp-action="Index" class="nav-link">Orders</a>
                            </li>
                            @if (ViewBag.nav == 2)
                            {
                                <li class="nav-item navAdLog">
                                    <a asp-action="Logout"  class="nav-link">Logout</a>
                                </li>
                            }
                            else
                            {

                            }
                        </ul>
                    </div>
                </div>
            </nav>

        }

    </header>
    <!--------------------Navigation bar------------------------->

    <div class="">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    @if (ViewBag.footer == 1)
    {
        <!--------------------footer------------------------->
        <footer class="border-top footer-sec ">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 ">
                        <p> เกี่ยวกับFilmLab </p> <br />
                        <a style="text-decoration: none; color: #734C36; " asp-controller="Home" asp-action="Privacy">นโยบายความเป็นส่วนตัว</a><br />
                        <p>ติดต่อเรา</p><br />
                        126 ถนนประชาอุทิศ แขวงบางมด<br />
                        เขตทุ่งครุ  กรุงเทพฯ 10140<br />
                        โทรศัพท์ : 0 2470 8000<br />
                        โทรสาร : 0 2427 9860<br />
                    </div>
                    <div class="col-sm-5">
                        <p>วิธีการชำระเงิน</p><br />
                        <img class="payicon" src="~/icon/KT.png" />
                        <img class="payicon" src="~/icon/SCB.png" />
                        <img class="payicon" src="~/icon/bbl.png" />
                        <img class="payicon" src="~/icon/KS.png" />
                        <img class="payicon" src="~/icon/BKK.png" />
                        <br />
                        <p>บริการจัดส่ง</p><br />
                        <img class="deliver" src="~/icon/thaipost.png" />
                        <img class="deliver" src="~/icon/kerry.png" />
                        <img class="deliver" src="~/icon/jte.png" />
                        <img class="deliver" src="~/icon/dhl2 1.png" />
                    </div>
                    <div class="col-sm-3 ">
                        <p>ติดตามเรา</p><br />
                        <img class="mdicon" src="~/icon/facebook.svg" href="#" />
                        <img class="mdicon" src="~/icon/instagram.svg" href="#" />
                        <img class="mdicon" src="~/icon/twitter.svg" href="#" />
                        <img class="mdicon" src="~/icon/line.svg" href="#" />
                        <br />
                        <img class="mdicon" src="~/icon/youtube.svg" href="#" />
                        <img class="mdicon" src="~/icon/linkedin.svg" href="#" />

                    </div>
                </div>
            </div>
        </footer>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>